apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    environment: prod
  name: column-detection-prod
  namespace: default
spec:
  minReadySeconds: 60
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: column-detection-prod
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: column-detection-prod
    spec:
      serviceAccountName: column-detection-dev-sa
      containers:
        - env:
            - name: DEPLOYMENT_ENV
              value: production
          image: 783952637912.dkr.ecr.us-east-2.amazonaws.com/column-detection-service:v2.3
          imagePullPolicy: IfNotPresent
          name: column-detection-service-prod
          ports:
            - containerPort: 8080
              name: server-port
              protocol: TCP
          resources:
            limits:
              ephemeral-storage: 20Gi
              nvidia.com/gpu: "1"
            requests:
              ephemeral-storage: 20Gi
              nvidia.com/gpu: "1"
          securityContext:
            capabilities:
              drop:
                - NET_RAW
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        nvidia.com/gpu.present: "true"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      tolerations:
        - key: "nvidia.com/gpu"
          value: "true"
          effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    loadBalancerClass: service.k8s.aws/nlb
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: map-migrated=migACLXAPHP5O
  name: column-detection-prod-service
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: column-detection-prod
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerClass: eks.amazonaws.com/nlb
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: column-detection-dev-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::783952637912:role/column-detection-irsa-role