apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    environment: dev
  name: column-detection-dev
  namespace: default
spec:
  minReadySeconds: 60
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: column-detection-dev
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: column-detection-dev
    spec:
      serviceAccountName: column-detection-dev-sa
      containers:
        - env:
            - name: DEPLOYMENT_ENV
              value: staging
          image: 227410688064.dkr.ecr.us-east-2.amazonaws.com/column-detection-service:206605c2c8a85c22caa0bd11d10681d24e950375
          imagePullPolicy: IfNotPresent
          name: column-detection-service-dev
          ports:
            - containerPort: 8080
              name: server-port
              protocol: TCP
          resources:
            limits:
              ephemeral-storage: 20Gi
              nvidia.com/gpu: "1"
            requests:
              ephemeral-storage: 20Gi
              nvidia.com/gpu: "1"
          securityContext:
            capabilities:
              drop:
                - NET_RAW
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          # --- Fluent Bit sidecar container ---
        - name: fluent-bit
          image: 379889217383.dkr.ecr.us-east-2.amazonaws.com/fluent-bit-custom:v24
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "0.25"
              memory: "512Mi"
            requests:
              cpu: "0.1"
              memory: "256Mi"
          env:
            - name: AWS_REGION
              value: us-east-2
          volumeMounts:
            - name: logs
              mountPath: /app/app-logs
              readOnly: true
            - name: fluent-bit-info
              mountPath: /fluent-bit/info
            - name: fluent-db
              mountPath: /app/tmp
            - name: fluent-logs
              mountPath: /var/log/os-responses
      dnsPolicy: ClusterFirst
      nodeSelector:
        nvidia.com/gpu.present: "true"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      volumes:
        - name: logs
          emptyDir: {}
        - name: fluent-bit-info
          emptyDir: {}
        - name: fluent-db
          emptyDir: {}
        - name: fluent-logs
          emptyDir: {}
      tolerations:
        - key: "nvidia.com/gpu"
          value: "true"
          effect: "NoSchedule"
