name: Deploy via Dispatch

on:
  repository_dispatch:
    types: [deploy-service]

permissions:
  contents: write

jobs:
  update-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Parse payload
        run: |
          echo "SERVICE=${{ github.event.client_payload.service }}" >> $GITHUB_ENV
          echo "ENV=${{ github.event.client_payload.env }}"         >> $GITHUB_ENV
          echo "TAG=${{ github.event.client_payload.image_tag }}"   >> $GITHUB_ENV
          echo "ACCOUNT=${{ github.event.client_payload.account }}" >> $GITHUB_ENV

      - name: Update deployment file and push
        run: |
          set -euo pipefail
        
          DEPLOY_FILE="deployment/${ACCOUNT}/${ENV}/${SERVICE}.yml"
          echo "🔎 Updating ${DEPLOY_FILE} to tag '${TAG}'"
        
          [ -f "$DEPLOY_FILE" ] || { echo "❌ Missing $DEPLOY_FILE"; exit 1; }

          # yq v4
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.44.1/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          /usr/local/bin/yq --version

          # Read current image from Deployment only
          CUR_IMAGE=$(/usr/local/bin/yq e 'select(.kind=="Deployment") | .spec.template.spec.containers[0].image' "$DEPLOY_FILE")
          [ -n "$CUR_IMAGE" ] && [ "$CUR_IMAGE" != "null" ] || { echo "❌ Could not read current image"; exit 1; }

          # Preserve repo, swap only tag
          if [[ "$CUR_IMAGE" == *:* ]]; then BASE="${CUR_IMAGE%:*}"; else BASE="$CUR_IMAGE"; fi
          export NEW_IMAGE="${BASE}:${TAG}"

          echo "OLD: $CUR_IMAGE"
          echo "NEW: $NEW_IMAGE"

          if [ "$CUR_IMAGE" = "$NEW_IMAGE" ]; then
            echo "ℹ️ Already at desired image. Nothing to change."
            exit 0
          fi

          # Precompute container name
          export TARGET_CONTAINER="${SERVICE}-${ENV}"

          # Update ONLY the Deployment doc; preserve everything else
          /usr/local/bin/yq -i 'select(.kind == "Deployment" and .metadata.name == env(TARGET_CONTAINER)) | .spec.template.spec.containers[] |= select(.name == env(TARGET_CONTAINER)).image = env(NEW_IMAGE)' "$DEPLOY_FILE"
          echo "🔁 Diff:"
          git --no-pager diff -- "$DEPLOY_FILE" || true

          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "$DEPLOY_FILE"
          git commit -m "chore: deploy ${SERVICE} to ${ENV} @ ${TAG} [skip ci]" || { echo "ℹ️ No changes to commit"; exit 0; }
          # Rebase onto latest main (handle concurrent updaters)
          for i in 1 2 3; do
            git fetch origin main
            if git pull --rebase --autostash origin main; then
               break
            fi
            echo "Rebase attempt $i failed; retrying..."
            sleep $((i*3))
          done
          #Push current HEAD to main
          git push origin HEAD:main
       
