name: Test AWS Secrets

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Test AWS Secrets
        run: |
          echo "Testing AWS secrets access..."
          if [ -n "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then
            echo "✅ AWS_ACCESS_KEY_ID is set"
            echo "Length: ${#AWS_ACCESS_KEY_ID}"
          else
            echo "❌ AWS_ACCESS_KEY_ID is NOT set"
          fi
          
          if [ -n "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]; then
            echo "✅ AWS_SECRET_ACCESS_KEY is set"
            echo "Length: ${#AWS_SECRET_ACCESS_KEY}"
          else
            echo "❌ AWS_SECRET_ACCESS_KEY is NOT set"
          fi
          
          echo "AWS_REGION: us-east-2 (hardcoded)" 